# Generated by Django 3.2.25 on 2024-07-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotapp', '0003_alter_order_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=None),
        ),
    ]
